spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: huangbentai
    url: jdbc:mysql:///platform?useSSL=false&characterEncoding=utf-8
  flyway:
    baseline-on-migrate: true
    baseline-version: 20230307001
